version: 2
updates:
    # Bun dependencies (production and development)
    - package-ecosystem: "bun"
      directory: "/"
      target-branch: "main"
      schedule:
          interval: "weekly"
      commit-message:
          prefix: "chore"
          include: "scope"
      rebase-strategy: "auto"
      open-pull-requests-limit: 10
      labels:
          - "dependencies"
          - "bun"
          - "javascript"
      groups:
          dev-dependencies:
              dependency-type: "development"
          production-minor-patch:
              dependency-type: "production"
              update-types: ["minor", "patch"]

    # GitHub Actions
    - package-ecosystem: "github-actions"
      directory: "/"
      target-branch: "main"
      schedule:
          interval: "weekly"
      commit-message:
          prefix: "chore(actions)"
          include: "scope"
      rebase-strategy: "auto"
      labels:
          - "dependencies"
          - "github-actions"

    # Docker
    - package-ecosystem: "docker"
      directory: "/"
      target-branch: "main"
      schedule:
          interval: "weekly"
      commit-message:
          prefix: "chore(docker)"
          include: "scope"
      rebase-strategy: "auto"
      labels:
          - "dependencies"
          - "docker"
