project_id_env: "CROWDIN_PROJECT_ID"
api_token_env: "CROWDIN_PERSONAL_TOKEN"
base_path: "." # repo root
preserve_hierarchy: false

files:
    - source: "/public/assets/locales/en/translation.json"
      translation: "/public/assets/locales/%two_letters_code%/translation.json"