files:
  - source: "public/assets/locales/en/translation.json"
    translation: "public/assets/locales/%two_letters_code%/translation.json"

languages_mapping:
  two_letters_code:
    fr-FR: fr
    es-ES: es
    de-DE: de
    pt-PT: pt
