# Crowdin configuration file
# See https://developer.crowdin.com/cli/configuration/

project_id_env: "CROWDIN_PROJECT_ID"
api_token_env: "CROWDIN_PERSONAL_TOKEN"
base_path: "."

files:
  - source: "public/assets/locales/en/translation.json"
    translation: "public/assets/locales/%two_letters_code%/%original_file_name%"

    # Map Crowdin regional locales to your repo folders
    languages_mapping:
      two_letters_code:
        fr-FR: fr
        es-ES: es
        de-DE: de
        pt-PT: pt

