/**
 * No Man's Sky themed ship name prefixes.
 * These are used to generate build names for saved configurations.
 */
export const SHIP_NAME_PREFIXES = [
	"Starfire",
	"Celestial",
	"Dawn of",
	"Silver",
	"Galactic",
	"Infinite",
	"Black Nebula",
	"Silent",
	"Solar",
	"Wings of",
	"Crusade of the",
	"Archangel",
	"Eternal",
	"Storm of",
	"Crown of the",
	"Starborn",
	"Eclipse",
	"Horizon of",
	"Light",
	"Shadow of the",
	"Valkyrie's",
	"Nova of the",
	"Aegis of",
	"Kingdom of the",
	"Nebula's",
	"Odyssey's",
	"Reign of the",
	"Golden",
	"Astral",
	"Fortress of the",
	"Dragon of the",
	"Empire's",
	"Blade of the",
	"Children of the",
	"Queen of",
	"Symphony of the",
	"Keeper of the",
	"Voidstar",
	"Legend of the",
	"Sunborn",
];

/**
 * No Man's Sky themed ship name suffixes.
 * These are used to generate build names for saved configurations.
 */
export const SHIP_NAME_SUFFIXES = [
	"Eternity",
	"Crusader",
	"Nebula",
	"Horizon",
	"Symphony",
	"Eclipse",
	"Rising",
	"Starfall",
	"Requiem",
	"Infinity",
	"First Flame",
	"Ascendant",
	"Voyager",
	"Dawn",
	"Void",
	"Monarch",
	"Sovereign",
	"Tomorrow",
	"Breaker",
	"Empire",
	"Promise",
	"Seven Suns",
	"Stars",
	"Heart",
	"Triumph",
	"Celestials",
	"Armada",
	"Dawnbreaker",
	"Dominion",
	"Burning Sky",
	"Cosmos",
	"Leviathan",
	"Glory",
	"Seventh Gate",
	"Starlight",
	"First Age",
	"Eternal Flame",
	"Silver Crown",
	"Dynasty",
];
