name: 'Setup Bun Environment'
description: 'Sets up Bun and installs dependencies'
inputs:
  bun-version:
    description: 'The version of Bun to use'
    required: false
    default: 'latest'

runs:
  using: "composite"
  steps:
    - name: Set up Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ inputs.bun-version }}

    - name: Install dependencies
      shell: bash
      run: bun install --frozen-lockfile
