const puppeteer = require("puppeteer");

(async () => {
	const browser = await puppeteer.launch({ headless: "new" });
	const page = await browser.newPage();

	try {
		// GitHub Actions may run on localhost:4173 by default for vite preview
		await page.setViewport({ width: 1280, height: 880 });

		// Set localStorage for the target origin before any of its scripts run
		await page.evaluateOnNewDocument(() => {
			localStorage.setItem(
				"gridState",
				JSON.stringify({
					state: {
						grid: {
							cells: [
								[
									{
										active: true,
										adjacency: "none",
										adjacency_bonus: 0,
										bonus: 0,
										image: "exosuit/refiner.webp",
										module: "PR",
										label: "Personal Refiner",
										sc_eligible: false,
										supercharged: false,
										tech: "refiner",
										total: 0,
										type: "core",
										value: 0,
									},
									{
										active: true,
										adjacency: "none",
										adjacency_bonus: 0,
										bonus: 0,
										image: "exosuit/skiff.webp",
										module: "ES",
										label: "Exo Skiff",
										sc_eligible: false,
										supercharged: false,
										tech: "skiff",
										total: 0,
										type: "core",
										value: 0,
									},
									{
										active: true,
										adjacency: "none",
										adjacency_bonus: 0,
										bonus: 0,
										image: "exosuit/hazmat.webp",
										module: "HG",
										label: "Haz-Mat Gauntlets",
										sc_eligible: false,
										supercharged: false,
										tech: "hazmat",
										total: 0,
										type: "core",
										value: 0,
									},
									{
										active: true,
										adjacency: "lesser",
										adjacency_bonus: 1,
										bonus: 0.29,
										image: "exosuit/rebuilt.webp",
										module: "Xb",
										label: "Rebuilt Exosuit Module Tau",
										sc_eligible: true,
										supercharged: false,
										tech: "rebuilt",
										total: 0,
										type: "bonus",
										value: 0,
									},
									{
										active: true,
										adjacency: "lesser",
										adjacency_bonus: 1,
										bonus: 0.3,
										image: "exosuit/forbidden.webp",
										module: "Xa",
										label: "Forbidden Exosuit Module Theta",
										sc_eligible: true,
										supercharged: true,
										tech: "forbidden",
										total: 0,
										type: "bonus",
										value: 0,
									},
									{
										active: true,
										adjacency: "greater",
										adjacency_bonus: 1,
										bonus: 0.29,
										image: "exosuit/defense.webp",
										module: "Xb",
										label: "Defense Systems Tau",
										sc_eligible: true,
										supercharged: false,
										tech: "defense",
										total: 0,
										type: "bonus",
										value: 0,
									},
									{
										active: true,
										adjacency: "greater",
										adjacency_bonus: 1,
										bonus: 0.29,
										image: "exosuit/coolant-upgrade.webp",
										module: "Xb",
										label: "Coolant Network Upgrade Tau",
										sc_eligible: true,
										supercharged: false,
										tech: "coolant",
										total: 0,
										type: "bonus",
										value: 0,
									},
									{
										active: true,
										adjacency: "none",
										adjacency_bonus: 1,
										bonus: 0,
										image: "exosuit/hazard.webp",
										module: "HP",
										label: "Hazard Protection",
										sc_eligible: false,
										supercharged: false,
										tech: "hazard",
										total: 0,
										type: "core",
										value: 0,
									},
									{
										active: true,
										adjacency: "none",
										adjacency_bonus: 1,
										bonus: 0,
										image: "exosuit/anomaly.webp",
										module: "AS",
										label: "Anomaly Suppressor",
										sc_eligible: false,
										supercharged: false,
										tech: "anomaly",
										total: 0,
										type: "core",
										value: 0,
									},
									{
										active: true,
										adjacency: "greater",
										adjacency_bonus: 1,
										bonus: 0.29,
										image: "exosuit/toxin-upgrade.webp",
										module: "Xb",
										label: "Toxin Suppressor Upgrade Tau",
										sc_eligible: true,
										supercharged: false,
										tech: "toxin",
										total: 0,
										type: "bonus",
										value: 0,
									},
								],
								[
									{
										active: true,
										adjacency: "none",
										adjacency_bonus: 1,
										bonus: 0,
										image: "exosuit/nutrient.webp",
										module: "NI",
										label: "Nutrient Ingestor",
										sc_eligible: false,
										supercharged: false,
										tech: "nutrient",
										total: 0,
										type: "core",
										value: 0,
									},
									{
										active: true,
										adjacency: "lesser",
										adjacency_bonus: 1,
										bonus: 1,
										image: "exosuit/jetpack.webp",
										module: "JP",
										label: "Jetpack",
										sc_eligible: false,
										supercharged: false,
										tech: "jetpack",
										total: 0,
										type: "core",
										value: 0,
									},
									{
										active: true,
										adjacency: "greater",
										adjacency_bonus: 1,
										bonus: 0,
										image: "exosuit/waterjets.webp",
										module: "WJ",
										label: "Efficient Water Jets",
										sc_eligible: true,
										supercharged: false,
										tech: "jetpack",
										total: 0,
										type: "bonus",
										value: 0,
									},
									{
										active: true,
										adjacency: "lesser",
										adjacency_bonus: 1,
										bonus: 0.3,
										image: "exosuit/rebuilt.webp",
										module: "Xa",
										label: "Rebuilt Exosuit Module Theta",
										sc_eligible: true,
										supercharged: false,
										tech: "rebuilt",
										total: 0,
										type: "bonus",
										value: 0,
									},
									{
										active: true,
										adjacency: "lesser",
										adjacency_bonus: 1,
										bonus: 0.29,
										image: "exosuit/forbidden.webp",
										module: "Xb",
										label: "Forbidden Exosuit Module Tau",
										sc_eligible: true,
										supercharged: false,
										tech: "forbidden",
										total: 0,
										type: "bonus",
										value: 0,
									},
									{
										active: true,
										adjacency: "greater",
										adjacency_bonus: 1,
										bonus: 0.3,
										image: "exosuit/defense.webp",
										module: "Xa",
										label: "Defense Systems Theta",
										sc_eligible: true,
										supercharged: false,
										tech: "defense",
										total: 0,
										type: "bonus",
										value: 0,
									},
									{
										active: true,
										adjacency: "greater",
										adjacency_bonus: 1,
										bonus: 0.3,
										image: "exosuit/coolant-upgrade.webp",
										module: "Xa",
										label: "Coolant Network Upgrade Theta",
										sc_eligible: true,
										supercharged: false,
										tech: "coolant",
										total: 0,
										type: "bonus",
										value: 0,
									},
									{
										active: true,
										adjacency: "greater",
										adjacency_bonus: 1,
										bonus: 1,
										image: "exosuit/protection.webp",
										module: "SL",
										label: "Sheild Lattice",
										sc_eligible: true,
										supercharged: false,
										tech: "protection",
										total: 0,
										type: "bonus",
										value: 0,
									},
									{
										active: true,
										adjacency: "greater",
										adjacency_bonus: 1,
										bonus: 0.3,
										image: "exosuit/protection-upgrade.webp",
										module: "Xa",
										label: "Sheild Lattice Upgrade Theta",
										sc_eligible: true,
										supercharged: true,
										tech: "protection",
										total: 0,
										type: "bonus",
										value: 0,
									},
									{
										active: true,
										adjacency: "greater",
										adjacency_bonus: 1,
										bonus: 0.3,
										image: "exosuit/toxin-upgrade.webp",
										module: "Xa",
										label: "Toxin Suppressor Upgrade Theta",
										sc_eligible: true,
										supercharged: false,
										tech: "toxin",
										total: 0,
										type: "bonus",
										value: 0,
									},
								],
								[
									{
										active: true,
										adjacency: "greater",
										adjacency_bonus: 1,
										bonus: 0,
										image: "exosuit/airburst.webp",
										module: "AB",
										label: "Airburst Engine",
										sc_eligible: true,
										supercharged: false,
										tech: "jetpack",
										total: 0,
										type: "bonus",
										value: 0,
									},
									{
										active: true,
										adjacency: "greater",
										adjacency_bonus: 1,
										bonus: 0.29,
										image: "exosuit/jetpack-upgrade.webp",
										module: "Xb",
										label: "Jetpack Upgrade Tau",
										sc_eligible: true,
										supercharged: false,
										tech: "jetpack",
										total: 0,
										type: "bonus",
										value: 0,
									},
									{
										active: true,
										adjacency: "greater",
										adjacency_bonus: 1,
										bonus: 0.3,
										image: "exosuit/jetpack-upgrade.webp",
										module: "Xa",
										label: "Jetpack Upgrade Theta",
										sc_eligible: true,
										supercharged: true,
										tech: "jetpack",
										total: 0,
										type: "bonus",
										value: 0,
									},
									{
										active: true,
										adjacency: "lesser",
										adjacency_bonus: 1,
										bonus: 0.28,
										image: "exosuit/rebuilt.webp",
										module: "Xc",
										label: "Rebuilt Exosuit Module Sigma",
										sc_eligible: true,
										supercharged: false,
										tech: "rebuilt",
										total: 0,
										type: "bonus",
										value: 0,
									},
									{
										active: true,
										adjacency: "lesser",
										adjacency_bonus: 1,
										bonus: 0.28,
										image: "exosuit/forbidden.webp",
										module: "Xc",
										label: "Forbidden Exosuit Module Sigma",
										sc_eligible: true,
										supercharged: false,
										tech: "forbidden",
										total: 0,
										type: "bonus",
										value: 0,
									},
									{
										active: true,
										adjacency: "greater",
										adjacency_bonus: 1,
										bonus: 0.28,
										image: "exosuit/defense.webp",
										module: "Xc",
										label: "Defense Systems Sigma",
										sc_eligible: true,
										supercharged: false,
										tech: "defense",
										total: 0,
										type: "bonus",
										value: 0,
									},
									{
										active: true,
										adjacency: "greater",
										adjacency_bonus: 1,
										bonus: 0.28,
										image: "exosuit/coolant-upgrade.webp",
										module: "Xc",
										label: "Coolant Network Upgrade Sigma",
										sc_eligible: true,
										supercharged: false,
										tech: "coolant",
										total: 0,
										type: "bonus",
										value: 0,
									},
									{
										active: true,
										adjacency: "greater",
										adjacency_bonus: 1,
										bonus: 0.29,
										image: "exosuit/protection-upgrade.webp",
										module: "Xb",
										label: "Sheild Lattice Upgrade Tau",
										sc_eligible: true,
										supercharged: false,
										tech: "protection",
										total: 0,
										type: "bonus",
										value: 0,
									},
									{
										active: true,
										adjacency: "greater",
										adjacency_bonus: 1,
										bonus: 0.28,
										image: "exosuit/protection-upgrade.webp",
										module: "Xc",
										label: "Sheild Lattice Upgrade Sigma",
										sc_eligible: true,
										supercharged: false,
										tech: "protection",
										total: 0,
										type: "bonus",
										value: 0,
									},
									{
										active: true,
										adjacency: "greater",
										adjacency_bonus: 1,
										bonus: 0.28,
										image: "exosuit/toxin-upgrade.webp",
										module: "Xc",
										label: "Toxin Suppressor Upgrade Sigma",
										sc_eligible: true,
										supercharged: false,
										tech: "toxin",
										total: 0,
										type: "bonus",
										value: 0,
									},
								],
								[
									{
										active: true,
										adjacency: "none",
										adjacency_bonus: 1,
										bonus: 0,
										image: "exosuit/exocraft.webp",
										module: "ES",
										label: "Exosuit Summoning Unit",
										sc_eligible: false,
										supercharged: false,
										tech: "exocraft",
										total: 0,
										type: "core",
										value: 0,
									},
									{
										active: true,
										adjacency: "greater",
										adjacency_bonus: 1,
										bonus: 0.1,
										image: "exosuit/neural.webp",
										module: "NS",
										label: "Neural Stimulator",
										sc_eligible: true,
										supercharged: false,
										tech: "jetpack",
										total: 0,
										type: "bonus",
										value: 0,
									},
									{
										active: true,
										adjacency: "greater",
										adjacency_bonus: 1,
										bonus: 0.28,
										image: "exosuit/jetpack-upgrade.webp",
										module: "Xc",
										label: "Jetpack Upgrade Sigma",
										sc_eligible: true,
										supercharged: false,
										tech: "jetpack",
										total: 0,
										type: "bonus",
										value: 0,
									},
									{
										active: true,
										adjacency: "lesser",
										adjacency_bonus: 1,
										bonus: 0,
										image: "exosuit/artemis-translator.webp",
										module: "Ta",
										label: "Artemis' Translator",
										sc_eligible: true,
										supercharged: false,
										tech: "translators",
										total: 0,
										type: "bonus",
										value: 0,
									},
									{
										active: true,
										adjacency: "lesser",
										adjacency_bonus: 1,
										bonus: 0,
										image: "exosuit/simple.webp",
										module: "Tb",
										label: "Simple Translator",
										sc_eligible: true,
										supercharged: false,
										tech: "translators",
										total: 0,
										type: "bonus",
										value: 0,
									},
									{
										active: true,
										adjacency: "greater",
										adjacency_bonus: 1,
										bonus: 0.29,
										image: "exosuit/aeration-upgrade.webp",
										module: "Xb",
										label: "Aeration Membrane Upgrade Tau",
										sc_eligible: true,
										supercharged: false,
										tech: "aeration",
										total: 0,
										type: "bonus",
										value: 0,
									},
									{
										active: true,
										adjacency: "greater",
										adjacency_bonus: 1,
										bonus: 0.29,
										image: "exosuit/radiation-upgrade.webp",
										module: "Xb",
										label: "Radiation Deflector Upgrade Tau",
										sc_eligible: true,
										supercharged: false,
										tech: "radiation",
										total: 0,
										type: "bonus",
										value: 0,
									},
									{
										active: true,
										adjacency: "greater",
										adjacency_bonus: 1,
										bonus: 1,
										image: "exosuit/coolant.webp",
										module: "CN",
										label: "Coolant Networt",
										sc_eligible: true,
										supercharged: false,
										tech: "coolant",
										total: 0,
										type: "bonus",
										value: 0,
									},
									{
										active: true,
										adjacency: "greater",
										adjacency_bonus: 1,
										bonus: 1,
										image: "exosuit/toxin.webp",
										module: "TS",
										label: "Toxin Suppressor",
										sc_eligible: true,
										supercharged: false,
										tech: "toxin",
										total: 0,
										type: "bonus",
										value: 0,
									},
									{
										active: true,
										adjacency: "greater",
										adjacency_bonus: 1,
										bonus: 0.29,
										image: "exosuit/thermic-upgrade.webp",
										module: "Xb",
										label: "Thermic Layer Upgrade Tau",
										sc_eligible: true,
										supercharged: false,
										tech: "thermic",
										total: 0,
										type: "bonus",
										value: 0,
									},
								],
								[
									{
										active: true,
										adjacency: "lesser",
										adjacency_bonus: 1,
										bonus: 0.28,
										image: "exosuit/life-upgrade.webp",
										module: "Xc",
										label: "Life Support Upgrade Sigma",
										sc_eligible: true,
										supercharged: false,
										tech: "life",
										total: 0,
										type: "bonus",
										value: 0,
									},
									{
										active: true,
										adjacency: "lesser",
										adjacency_bonus: 1,
										bonus: 0.29,
										image: "exosuit/life-upgrade.webp",
										module: "Xb",
										label: "Life Support Upgrade Tau",
										sc_eligible: true,
										supercharged: false,
										tech: "life",
										total: 0,
										type: "bonus",
										value: 0,
									},
									{
										active: true,
										adjacency: "none",
										adjacency_bonus: 0,
										bonus: 0,
										image: "exosuit/rerouter.webp",
										module: "RR",
										label: "Oxygen Rereouter",
										sc_eligible: true,
										supercharged: false,
										tech: "life",
										total: 0,
										type: "bonus",
										value: 0,
									},
									{
										active: true,
										adjacency: "lesser",
										adjacency_bonus: 1,
										bonus: 0,
										image: "exosuit/superior.webp",
										module: "Tc",
										label: "Superior Translator",
										sc_eligible: true,
										supercharged: false,
										tech: "translators",
										total: 0,
										type: "bonus",
										value: 0,
									},
									{
										active: true,
										adjacency: "lesser",
										adjacency_bonus: 1,
										bonus: 0,
										image: "exosuit/advanced.webp",
										module: "Td",
										label: "Advanced Translator",
										sc_eligible: true,
										supercharged: false,
										tech: "translators",
										total: 0,
										type: "bonus",
										value: 0,
									},
									{
										active: true,
										adjacency: "greater",
										adjacency_bonus: 1,
										bonus: 0.3,
										image: "exosuit/aeration-upgrade.webp",
										module: "Xa",
										label: "Aeration Membrane Upgrade Theta",
										sc_eligible: true,
										supercharged: false,
										tech: "aeration",
										total: 0,
										type: "bonus",
										value: 0,
									},
									{
										active: true,
										adjacency: "greater",
										adjacency_bonus: 1,
										bonus: 0.3,
										image: "exosuit/radiation-upgrade.webp",
										module: "Xa",
										label: "Radiation Deflector Upgrade Theta",
										sc_eligible: true,
										supercharged: false,
										tech: "radiation",
										total: 0,
										type: "bonus",
										value: 0,
									},
									{
										active: true,
										adjacency: "greater",
										adjacency_bonus: 1,
										bonus: 1,
										image: "exosuit/radiation.webp",
										module: "RD",
										label: "Radiation Deflector",
										sc_eligible: true,
										supercharged: false,
										tech: "radiation",
										total: 0,
										type: "bonus",
										value: 0,
									},
									{
										active: true,
										adjacency: "greater",
										adjacency_bonus: 1,
										bonus: 1,
										image: "exosuit/thermic.webp",
										module: "TL",
										label: "Thermic Layer",
										sc_eligible: true,
										supercharged: false,
										tech: "thermic",
										total: 0,
										type: "bonus",
										value: 0,
									},
									{
										active: true,
										adjacency: "greater",
										adjacency_bonus: 1,
										bonus: 0.3,
										image: "exosuit/thermic-upgrade.webp",
										module: "Xa",
										label: "Thermic Layer Upgrade Theta",
										sc_eligible: true,
										supercharged: false,
										tech: "thermic",
										total: 0,
										type: "bonus",
										value: 0,
									},
								],
								[
									{
										active: true,
										adjacency: "lesser",
										adjacency_bonus: 1,
										bonus: 0.3,
										image: "exosuit/life-upgrade.webp",
										module: "Xa",
										label: "Life Support Upgrade Theta",
										sc_eligible: true,
										supercharged: false,
										tech: "life",
										total: 0,
										type: "bonus",
										value: 0,
									},
									{
										active: true,
										adjacency: "lesser",
										adjacency_bonus: 1,
										bonus: 1,
										image: "exosuit/life.webp",
										module: "LS",
										label: "Life Support",
										sc_eligible: false,
										supercharged: false,
										tech: "life",
										total: 0,
										type: "core",
										value: 0,
									},
									{
										active: true,
										adjacency: "lesser",
										adjacency_bonus: 1,
										bonus: 0.1,
										image: "exosuit/recycler.webp",
										module: "OR",
										label: "Oxygen Recycler",
										sc_eligible: true,
										supercharged: false,
										tech: "life",
										total: 0,
										type: "bonus",
										value: 0,
									},
									{
										active: true,
										adjacency: "none",
										adjacency_bonus: 1,
										bonus: 0,
										image: "exosuit/remembrance.webp",
										module: "RM",
										label: "Remembrance",
										sc_eligible: false,
										supercharged: false,
										tech: "remembrance",
										total: 0,
										type: "core",
										value: 0,
									},
									{
										active: true,
										adjacency: "none",
										adjacency_bonus: 1,
										bonus: 0,
										image: "exosuit/starseed.webp",
										module: "SS",
										label: "Star Seed",
										sc_eligible: false,
										supercharged: false,
										tech: "starseed",
										total: 0,
										type: "core",
										value: 0,
									},
									{
										active: true,
										adjacency: "greater",
										adjacency_bonus: 1,
										bonus: 0.28,
										image: "exosuit/aeration-upgrade.webp",
										module: "Xc",
										label: "Aeration Membrane Upgrade Sigma",
										sc_eligible: true,
										supercharged: false,
										tech: "aeration",
										total: 0,
										type: "bonus",
										value: 0,
									},
									{
										active: true,
										adjacency: "greater",
										adjacency_bonus: 1,
										bonus: 1,
										image: "exosuit/aeration.webp",
										module: "AM",
										label: "Aeration Membrane",
										sc_eligible: true,
										supercharged: false,
										tech: "aeration",
										total: 0,
										type: "bonus",
										value: 0,
									},
									{
										active: true,
										adjacency: "greater",
										adjacency_bonus: 1,
										bonus: 0.28,
										image: "exosuit/radiation-upgrade.webp",
										module: "Xc",
										label: "Radiation Deflector Upgrade Sigma",
										sc_eligible: true,
										supercharged: false,
										tech: "radiation",
										total: 0,
										type: "bonus",
										value: 0,
									},
									{
										active: true,
										adjacency: "greater",
										adjacency_bonus: 1,
										bonus: 0.28,
										image: "exosuit/thermic-upgrade.webp",
										module: "Xc",
										label: "Thermic Layer Upgrade Sigma",
										sc_eligible: true,
										supercharged: false,
										tech: "thermic",
										total: 0,
										type: "bonus",
										value: 0,
									},
									{
										active: true,
										adjacency: "none",
										adjacency_bonus: 1,
										bonus: 0,
										image: "exosuit/pressure.webp",
										module: "PM",
										label: "Pressure Membrane",
										sc_eligible: false,
										supercharged: false,
										tech: "pressure",
										total: 0,
										type: "core",
										value: 0,
									},
								],
							],
							width: 10,
							height: 6,
						},
						isSharedGrid: false,
						gridFixed: false,
						superchargedFixed: true,
						initialGridDefinition: {
							grid: [
								[
									{
										active: true,
									},
									{
										active: true,
									},
									{
										active: true,
									},
									{
										active: true,
									},
									{
										active: true,
										supercharged: true,
									},
									{
										active: true,
									},
									{
										active: true,
									},
									{
										active: true,
									},
									{
										active: true,
									},
									{
										active: true,
									},
								],
								[
									{
										active: true,
									},
									{
										active: true,
									},
									{
										active: true,
									},
									{
										active: true,
									},
									{
										active: true,
									},
									{
										active: true,
									},
									{
										active: true,
									},
									{
										active: true,
									},
									{
										active: true,
										supercharged: true,
									},
									{
										active: true,
									},
								],
								[
									{
										active: true,
									},
									{
										active: true,
									},
									{
										active: true,
										supercharged: true,
									},
									{
										active: true,
									},
									{
										active: true,
									},
									{
										active: true,
									},
									{
										active: true,
									},
									{
										active: true,
									},
									{
										active: true,
									},
									{
										active: true,
									},
								],
								[
									{
										active: true,
									},
									{
										active: true,
									},
									{
										active: true,
									},
									{
										active: true,
									},
									{
										active: true,
									},
									{
										active: true,
									},
									{
										active: true,
									},
									{
										active: true,
									},
									{
										active: true,
									},
									{
										active: true,
									},
								],
								[
									{
										active: true,
									},
									{
										active: true,
									},
									{
										active: true,
									},
									{
										active: true,
									},
									{
										active: true,
									},
									{
										active: true,
									},
									{
										active: true,
									},
									{
										active: true,
									},
									{
										active: true,
									},
									{
										active: true,
									},
								],
								[
									{
										active: true,
									},
									{
										active: true,
									},
									{
										active: true,
									},
									{
										active: true,
									},
									{
										active: true,
									},
									{
										active: true,
									},
									{
										active: true,
									},
									{
										active: true,
									},
									{
										active: true,
									},
									{
										active: true,
									},
								],
							],
							gridFixed: false,
							superchargedFixed: true,
						},
						selectedPlatform: "exosuit",
					},
					version: 0,
				})
			);
			localStorage.setItem("selectedPlatform", "exosuit");
		});

		await page.goto("http://localhost:4173", { waitUntil: "networkidle0" });
		await page.screenshot({ path: "public/assets/img/screenshots/screenshot.png", fullPage: true });
		console.log("Taking standard screenshot ...");
		await page.screenshot({
			path: "public/assets/img/screenshots/screenshot_desktop.png",
			fullPage: true,
		});

		await page.setViewport({ width: 375, height: 667 });
		await page.goto("http://localhost:4173", { waitUntil: "networkidle0" });
		console.log("Taking mobile screenshot ...");
		await page.screenshot({
			path: "public/assets/img/screenshots/screenshot_mobile.png",
			fullPage: false,
		});

		await page.setViewport({ width: 800, height: 1280 });
		await page.goto("http://localhost:4173", { waitUntil: "networkidle0" });
		console.log("Taking tablet screenshot ...");
		await page.screenshot({
			path: "public/assets/img/screenshots/screenshot_tablet.png",
			fullPage: false,
		});
	} finally {
		await browser.close();
	}
})();
